# Use an official Python runtime as a parent image
FROM python:3.10.13-slim-bookworm

WORKDIR /app
COPY . /app

# Install netcat (nc) for healthcheck
RUN apt-get update && apt-get install -y \
    netcat-traditional  \
    telnet \
    && rm -rf /var/lib/apt/lists/*

    RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY server.py .

# Expose port 65432 for the server
EXPOSE 65432

# Run the server script
CMD ["python", "server.py"]
