# Use an official Python runtime as a parent image
FROM python:3.10.13-slim-bookworm

# Install netcat (nc) for healthcheck
RUN apt-get update && apt-get install -y \
    netcat-traditional  \
    telnet \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the server script into the container at /app
COPY server.py .

# Expose port 65432 for the server
EXPOSE 65432

# Run the server script
CMD ["python", "server.py"]
