version: '3.1'
services:
  # Server service
  OMserver:
    build:
      context: .
      dockerfile: ./Dockerfile.OMserver  # Dockerfile for the server
    image: omserver-image
    container_name: OMserver
    ports:
      - "65432:65432"  # Expose server port
    networks:
      - trading_network
    command: ["python3", "server.py"]  # Command to run the server script
    stdin_open: true
    tty: true

  # Client service
  TVwebhook:
    build:
      context: .
      dockerfile: ./Dockerfile.TVwebhook  # Dockerfile for the client
    image: tvwebhook-image
    container_name: TVwebhook
    command: ["python3", "TVwebhook.py"]
    stdin_open: true
    tty: true
    networks:
      - trading_network
    depends_on:
      - OMserver  # Ensure client starts after server is up
    volumes:
      - .:/app

networks:
  trading_network:
    driver: bridge
